[package]
name = "day4-rust"
version = "0.1.0"
authors = ["Joel Miller <miller345@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
